//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beer
    {
        public Beer()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public int ID { get; set; }
        public int BreweryID { get; set; }
        public int StyleID { get; set; }
        public string Name { get; set; }
        public Nullable<float> ABV { get; set; }
        public Nullable<int> IBU { get; set; }
        public Nullable<int> SRM { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<int> OldBreweryID { get; set; }
        public Nullable<int> OldStyleID { get; set; }
        public Nullable<int> OldID { get; set; }
    
        public virtual Brewery Brewery { get; set; }
        public virtual Style Style { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
