//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Styles = new HashSet<Style>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> OldID { get; set; }
    
        public virtual ICollection<Style> Styles { get; set; }
    }
}
