//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Breweries = new HashSet<Brewery>();
        }
    
        public int ID { get; set; }
        public int AddressID { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> OldBreweryID { get; set; }
        public byte[] IsPrimary { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Brewery> Breweries { get; set; }
    }
}
