//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int BeerID { get; set; }
        public Nullable<int> Simple { get; set; }
        public Nullable<int> Appearance { get; set; }
        public Nullable<int> Aroma { get; set; }
        public Nullable<int> Taste { get; set; }
        public Nullable<double> Overall { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public byte[] Modified { get; set; }
    
        public virtual Beer Beer { get; set; }
    }
}
